# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: riezebosch.Packer.PackerTool.PackerTool@0
  displayName: 'get packer 1.3.2'
  inputs:
    version: 1.3.2


- task: riezebosch.Packer.Packer.Packer@1
  displayName: 'packer-validate'
  inputs:
    azureSubscription: 'packer-infra4711'

    templatePath: ubuntu1804.json

    command: validate

- task: riezebosch.Packer.Packer.Packer@1
  displayName: 'packer-build'
  inputs:
    azureSubscription: 'packer-infra4711'

    templatePath: ubuntu1804.json

    command: build