# ASP.NET Core build
queue:
  name: Hosted VS2017
  demands: 
  - msbuild
  - visualstudio
variables:
  BuildSolution: 'Downloader.sln'
  BuildPlatform: 'any cpu'
  BuildConfiguration: 'Release'
  RestoreBuildProjects: 'Downloader/*.csproj'
  
steps:
- task: VSBuild@1
  displayName: 'Build solution'
  inputs:
    solution: '$(BuildSolution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=True /p:publishUrl="$(Agent.TempDirectory)\WebAppContent\\"'
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
